networks:
  plapi:

services:
  app:
    image: ghcr.io/hpware/esp32-postgres-logger-view-and-api:main
    restart: always
    networks:
      plapi:
    environment:
      - POSTGRES_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@pgdb:5432/${POSTGRES_DB:-postgres}
      - S3_URL=http://s3:9000
      - S3_BUCKET=esp32-logger
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID:-minioadmin}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY:-minioadmin}
    ports:
      - "8822:3000"
    depends_on:
      - pgdb
      - s3
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    networks:
      plapi:
    command: tunnel --no-autoupdate run --token 
    depends_on:
      - app
  pgdb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      plapi:
    volumes:
      - ./pg-data:/var/lib/postgresql/data
  s3:
    image: minio/minio:latest
    restart: always
    volumes:
      - ./s3-data:/data
    networks:
      plapi:
    ports:
      - 24830:9000
      - 24831:24831
    command: server /data --console-address ":24831"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5
    # CHANGE YOU CREDENTIALS HERE
    environment:
      MINIO_ROOT_USER: c9zzj
      MINIO_ROOT_PASSWORD: miniORjf0jzzise9jzoadminc39
      MINI_BROWSER_REDIRECT: false
  s3-init:
    image: minio/mc
    depends_on:
      s3:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID:-minioadmin}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY:-minioadmin}
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://s3:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb myminio/esp32-logger;
      /usr/bin/mc policy set public myminio/esp32-logger;
      exit 0;
      "